unbind C-b
set -g prefix C-s
bind-key C-s send-prefix
set -g allow-passthrough on
set -g mouse on

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g status-position top
set -g status-style "bg=#1c1c1c"
set -g status-justify left

set -g status-left " "
set -g status-right "#[fg=#6c7086,bg=#1c1c1c]  #{pane_current_command} "
set -g status-right-length 50

set -g window-status-format "#[fg=#2a2b3d,bg=#1c1c1c]#[fg=#6c7086,bg=#2a2b3d] #I: #W #[fg=#2a2b3d,bg=#1c1c1c]"
set -g window-status-current-format "#[fg=#ff9e64,bg=#1c1c1c]#[fg=#1c1c1c,bg=#ff9e64] #I: #W #[fg=#ff9e64,bg=#1c1c1c]"

set -g window-status-separator " "

set -g pane-border-style "fg=#2a2b3d"
set -g pane-active-border-style "fg=#ff9e64"

set -g message-style "fg=#d0d0d0,bg=#2a2b3d"
set -g message-command-style "fg=#d0d0d0,bg=#2a2b3d"
